home_path:
    path: /
    controller: App\Controller\HomeController::index

properties_index_path:
    path: /biens
    controller: App\Controller\PropertyController::index

property_show_path:
    path: /biens/{slug}-{id}
    controller: App\Controller\PropertyController::show
    requirements:
        slug: '[a-z0-9\-]*'